### ISSUE TITLE
restart required before step 16

### ISSUE THREAD

**Issue by larsyunker** [KornelJahn/truenas-core-tailscale-jail#1]
Thanks for the guide, this (eventually) worked perfectly for me, However, I had to restart my TrueNAS host system before the webui and smb would work properly. I'm not sure exactly which step needs the restart (my guess is step 14/15), but maybe it's worth adding a note before or in step 16 that `A restart of the host system may be required`.

**Comment by KornelJahn** [comment]
Thanks! Fixed in [954a372](https://github.com/KornelJahn/truenas-core-tailscale-jail/commit/954a37280381e9632702ac3ee43a56221ee616a1).
