### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by Lovedeep-s** [KornelJahn/truenas-core-tailscale-jail#2]
pkg error no package found "tailscale"

**Comment by crackinx** [comment]
> pkg error no package found "tailscale"

go to your Jail's shell and edit the file /etc/pkg/FreeBSD.conf
You want to change the line url: "pkg+http://pkg.FreeBSD.org/${ABI}/quarterly", so that it says url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest",

**Comment by KornelJahn** [comment]
Fixed by 8c2bdbcf3eb5ae6e311626969308c686f32076c6.
